In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('/content/spam.csv', encoding='ISO-8859-1')
df.head()

,Category,Message,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [5]:
df.describe()

,Category,Message,Unnamed: 2,Unnamed: 3,Unnamed: 4
count,5572,5572,50,12,6
unique,2,5169,43,10,5
top,ham,"Sorry, I'll call later","bt not his girlfrnd... G o o d n i g h t . . .@""","MK17 92H. 450Ppw 16""","GNT:-)"""
freq,4825,30,3,2,2

In [6]:
df.Category.value_counts()

ham     4825
spam     747
Name: Category, dtype: int64

In [7]:
df.shape

(5572, 5)

Lambda funtion using function

In [8]:
def get_spam_num(x):
  if x=='spam':
    return 1
  return 0

In [9]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)

In [10]:
df.head()

,Category,Message,Unnamed: 2,Unnamed: 3,Unnamed: 4,spam
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN,0
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN,0
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN,1
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN,0
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN,0

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [13]:
X_train.shape

(4457,)

In [14]:
X_test.shape

(1115,)

In [15]:
type(X_train)

pandas.core.series.Series

In [16]:
X_train[:6]

2139    But i juz remembered i gotta bathe my dog today..
4836           ....photoshop makes my computer shut down.
5529                            What about this one then.
767                                Sorry, I'll call later
4323                       I am not having her number sir
1800    excellent. I spent  &lt;#&gt;  years in the Ai...
Name: Message, dtype: object

In [18]:
X_train[:6][2139]

'But i juz remembered i gotta bathe my dog today..'

In [19]:
from sklearn.feature_extraction.text import CountVectorizer

Creating Bag of Words. That means create a vector for each email and count word frequency in email(Bow)

In [20]:
v = CountVectorizer()
X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<4457x7771 sparse matrix of type '<class 'numpy.int64'>'
	with 59192 stored elements in Compressed Sparse Row format>

In [21]:
X_train_cv.toarray()[0:4][0]

array([0, 0, 0, ..., 0, 0, 0])

to know number of unique word in vocabulary

In [22]:
X_train_cv.shape #7674 unique word in vocabulary

(4457, 7771)

In [23]:
v.get_feature_names_out()[1000:1050]

array(['anywhere', 'aom', 'apart', 'apartment', 'apes', 'aphexåõs',
       'apnt', 'apo', 'apologetic', 'apologise', 'apologize', 'apology',
       'app', 'apparently', 'appeal', 'appear', 'appendix',
       'applausestore', 'apples', 'application', 'apply', 'appointment',
       'appreciate', 'appreciated', 'approaches', 'approaching',
       'appropriate', 'approve', 'approved', 'approx', 'apps', 'appt',
       'appy', 'april', 'aproach', 'apt', 'aquarius', 'ar', 'arab',
       'arabian', 'arcade', 'archive', 'ard', 'are', 'area', 'aren',
       'arent', 'arestaurant', 'aretaking', 'areyouunique'], dtype=object)

In [24]:
v.get_feature_names_out().shape

(7771,)

In [25]:
v.vocabulary_

{'but': 1576,
 'juz': 3886,
 'remembered': 5691,
 'gotta': 3210,
 'bathe': 1242,
 'my': 4660,
 'dog': 2389,
 'today': 6950,
 'photoshop': 5192,
 'makes': 4325,
 'computer': 1946,
 'shut': 6150,
 'down': 2429,
 'what': 7490,
 'about': 748,
 'this': 6865,
 'one': 4932,
 'then': 6839,
 'sorry': 6337,
 'll': 4167,
 'call': 1608,
 'later': 4036,
 'am': 923,
 'not': 4822,
 'having': 3366,
 'her': 3413,
 'number': 4852,
 'sir': 6189,
 'excellent': 2699,
 'spent': 6386,
 'lt': 4252,
 'gt': 3266,
 'years': 7695,
 'in': 3644,
 'the': 6829,
 'air': 870,
 'force': 2951,
 'iraq': 3746,
 'and': 951,
 'afghanistan': 837,
 'stable': 6436,
 'honest': 3482,
 'do': 2374,
 'you': 7720,
 'like': 4116,
 'traveling': 7040,
 'kallis': 3898,
 'is': 3753,
 'ready': 5598,
 'for': 2950,
 'bat': 1238,
 '2nd': 397,
 'innings': 3689,
 'uncles': 7155,
 'atlanta': 1117,
 'wish': 7553,
 'guys': 3288,
 'great': 3240,
 'semester': 6014,
 'rt': 5850,
 'king': 3951,
 'pro': 5424,
 'video': 7298,
 'club': 1858,
 'need': 4723,
 'help': 3402,
 'info': 3678,
 'ringtoneking': 5800,
 'co': 1873,
 'uk': 7139,
 'or': 4969,
 '08701237397': 76,
 'must': 4652,
 'be': 1265,
 '16': 310,
 'credits': 2079,
 'redeemable': 5648,
 'at': 1113,
 'www': 7652,
 'enjoy': 2603,
 'thanx': 6821,
 'puttin': 5510,
 'da': 2147,
 'fone': 2937,
 'on': 4927,
 'me': 4410,
 'someone': 6306,
 'has': 3350,
 'conacted': 1949,
 'our': 5001,
 'dating': 2180,
 'service': 6039,
 'entered': 2612,
 'your': 7724,
 'phone': 5184,
 'because': 1276,
 'they': 6850,
 'fancy': 2780,
 'to': 6943,
 'find': 2864,
 'out': 5004,
 'who': 7510,
 'it': 3763,
 'from': 3029,
 'landline': 4011,
 '09111030116': 250,
 'pobox12n146tf15': 5263,
 'road': 5811,
 'so': 6289,
 'cant': 1643,
 'txt': 7112,
 'except': 2700,
 'theres': 6844,
 'chick': 1778,
 'with': 7560,
 'huge': 3546,
 'boobs': 1429,
 '1apple': 320,
 'day': 2184,
 'no': 4789,
 'doctor': 2380,
 '1tulsi': 334,
 'leaf': 4062,
 'cancer': 1638,
 '1lemon': 327,
 'fat': 2793,
 '1cup': 322,
 'milk': 4481,
 'bone': 1425,
 'problms': 5430,
 'litres': 4157,
 'watr': 7422,
 'diseases': 2351,
 'snd': 6278,
 'ths': 6890,
 'whom': 7512,
 'care': 1653,
 'where': 7499,
 'boytoy': 1480,
 'miss': 4509,
 'happened': 3334,
 'anyway': 998,
 'going': 3174,
 'shopping': 6117,
 'own': 5031,
 'now': 4837,
 'cos': 2025,
 'sis': 6190,
 'done': 2409,
 'yet': 7708,
 'dun': 2486,
 'disturb': 2358,
 'liao': 4098,
 'yup': 7743,
 'he': 3371,
 'msg': 4616,
 'tat': 6723,
 'yijue': 7712,
 'tot': 7004,
 'group': 3256,
 'mate': 4382,
 'we': 7433,
 'meeting': 4429,
 'mah': 4313,
 'askin': 1092,
 'if': 3606,
 'ì_': 7759,
 'leaving': 4069,
 'earlier': 2504,
 'wat': 7412,
 'mayb': 4403,
 'haf': 3300,
 'walk': 7377,
 'far': 2785,
 'there': 6843,
 'are': 1043,
 'other': 4994,
 'charges': 1734,
 'after': 841,
 'transfer': 7030,
 'can': 1631,
 'withdraw': 7561,
 'anyhow': 988,
 'wah': 7362,
 'okie': 4914,
 'muz': 4657,
 'make': 4324,
 'use': 7234,
 'of': 4888,
 'unlimited': 7188,
 'haha': 3301,
 'have': 3361,
 'registered': 5670,
 'sinco': 6178,
 'as': 1081,
 'payee': 5120,
 'log': 4184,
 'icicibank': 3590,
 'com': 1905,
 'enter': 2611,
 'urn': 7228,
 'confirm': 1963,
 'beware': 1335,
 'frauds': 2990,
 'share': 6075,
 'disclose': 2344,
 'anyone': 990,
 'give': 3150,
 'us': 7230,
 'back': 1191,
 'id': 3593,
 'proof': 5457,
 'rs': 5848,
 'wont': 7596,
 'allow': 905,
 'work': 7603,
 'will': 7532,
 'come': 1911,
 'home': 3479,
 'within': 7563,
 'days': 2185,
 'vikky': 7306,
 'around': 1065,
 'time': 6911,
 'want': 7391,
 'mapquest': 4351,
 'something': 6312,
 'look': 4201,
 'up': 7199,
 'usf': 7239,
 'dogwood': 2396,
 'drive': 2453,
 'ok': 4910,
 'lar': 4023,
 'joking': 3852,
 'wif': 7523,
 'oni': 4934,
 'plz': 5255,
 'note': 4823,
 'calling': 1619,
 'mobile': 4542,
 'amp': 939,
 'asks': 1094,
 'type': 7126,
 'disconnect': 2345,
 'coz': 2054,
 'iz': 3779,
 'an': 947,
 'attempt': 1123,
 'terrorist': 6790,
 'sim': 6171,
 'card': 1651,
 'itz': 3773,
 'confirmd': 1964,
 'by': 1589,
 'nokia': 4798,
 'motorola': 4597,
 'been': 1287,
 'verified': 7283,
 'cnn': 1871,
 'ibn': 3584,
 'specially': 6375,
 'selected': 6004,
 'receive': 5625,
 '3000': 416,
 'award': 1162,
 '08712402050': 106,
 'before': 1293,
 'lines': 4133,
 'close': 1849,
 'cost': 2027,
 '10ppm': 265,
 'cs': 2098,
 'apply': 1020,
 'ag': 846,
 'promo': 5453,
 'gsoh': 3265,
 'good': 3186,
 'spam': 6362,
 'ladies': 4000,
 'could': 2036,
 'male': 4331,
 'gigolo': 3140,
 'join': 3846,
 'fastest': 2792,
 'growing': 3258,
 'mens': 4447,
 'reply': 5721,
 'oncall': 4929,
 'mjzgroup': 4526,
 '08714342399': 116,
 '2stop': 404,
 'stop': 6502,
 '50rcvd': 537,
 'lol': 4192,
 'these': 6845,
 'ideas': 3597,
 'babes': 1183,
 'think': 6857,
 'got': 3204,
 'ur': 7216,
 'brolly': 1525,
 'left': 4073,
 'english': 2602,
 'wil': 7528,
 'bring': 1513,
 '2mrw': 396,
 'luv': 4266,
 'franxx': 2988,
 'might': 4476,
 'accidant': 767,
 'tookplace': 6984,
 'between': 1332,
 'somewhere': 6317,
 'ghodbandar': 3132,
 'rd': 5587,
 'traffic': 7020,
 'moves': 4604,
 'slovely': 6240,
 'slip': 6235,
 'don': 2407,
 'worry': 7614,
 'bus': 1572,
 'way': 7428,
 'calicut': 1606,
 'ill': 3619,
 'drink': 2448,
 'pa': 5038,
 'doing': 2399,
 'srs': 6431,
 'model': 4554,
 'pls': 5250,
 'send': 6018,
 'mail': 4317,
 'oi': 4906,
 'ami': 928,
 'parchi': 5076,
 'na': 4668,
 're': 5589,
 'kicchu': 3935,
 'kaaj': 3890,
 'korte': 3978,
 'iccha': 3588,
 'korche': 3976,
 'ta': 6685,
 'tul': 7092,
 'joys': 3864,
 'lifeis': 4108,
 'waking': 7374,
 'each': 2501,
 'daywith': 2186,
 'thoughts': 6876,
 'that': 6823,
 'somewheresomeone': 6318,
 'cares': 1660,
 'enough': 2610,
 'tosend': 7002,
 'warm': 7398,
 'morning': 4585,
 'greeting': 3245,
 'huh': 3549,
 'thk': 6866,
 'more': 4581,
 'oredi': 4979,
 'how': 3526,
 'many': 4349,
 'pages': 5046,
 'very': 7288,
 'its': 3770,
 'all': 900,
 'making': 4328,
 'money': 4567,
 'hey': 3424,
 'girl': 3144,
 'hope': 3494,
 'well': 7471,
 'del': 2231,
 'bak': 1203,
 'again': 847,
 'long': 4197,
 'sum': 6600,
 'lucyxx': 4259,
 'alright': 913,
 'see': 5992,
 'bit': 1368,
 'lmao': 4169,
 'take': 6697,
 'pic': 5196,
 '80488': 632,
 '500': 529,
 'free': 2995,
 'text': 6798,
 'messages': 4462,
 'valid': 7258,
 'until': 7198,
 '31': 425,
 'december': 2203,
 '2005': 345,
 'thank': 6815,
 'better': 1329,
 'cause': 1688,
 'feel': 2814,
 'used': 7235,
 'otherwise': 4996,
 'package': 5041,
 'programs': 5444,
 'happening': 3335,
 'gotten': 3211,
 'job': 3840,
 'begun': 1299,
 'registration': 5671,
 'permanent': 5152,
 'residency': 5742,
 'any': 986,
 'movie': 4605,
 'theatre': 6831,
 'go': 3163,
 'watch': 7413,
 'movies': 4606,
 'just': 3883,
 'pay': 5116,
 'once': 4930,
 'network': 4743,
 'operator': 4955,
 'visit': 7322,
 'biz': 1373,
 'private': 5418,
 '2003': 343,
 'account': 773,
 'statement': 6465,
 'shows': 6142,
 '800': 622,
 'un': 7150,
 'redeemed': 5649,
 'points': 5280,
 '08718738002': 154,
 'identifier': 3599,
 'code': 1883,
 '48922': 499,
 'expires': 2726,
 '21': 351,
 '11': 267,
 '04': 14,
 'too': 6982,
 'baby': 1185,
 'promise': 5450,
 'treat': 7046,
 'bet': 1326,
 'im': 3621,
 'realy': 5609,
 'soz': 6356,
 'imat': 3626,
 'mums': 4641,
 '2nite': 400,
 '2moro': 390,
 'ha': 3295,
 'nan': 4686,
 'yalrigu': 7682,
 'heltini': 3409,
 'iyo': 3778,
 'kothi': 3980,
 'chikku': 1782,
 'shared': 6076,
 'things': 6856,
 'wit': 7559,
 'didn': 2300,
 'told': 6960,
 'body': 1418,
 'even': 2663,
 'uttered': 7248,
 'word': 7601,
 'abt': 756,
 'trusting': 7073,
 'much': 4631,
 'tell': 6765,
 'others': 4995,
 'nxt': 4865,
 'dont': 2411,
 'those': 6871,
 'words': 7602,
 'hi': 3428,
 'sexychat': 6055,
 'girls': 3147,
 'waiting': 7372,
 'them': 6836,
 'night': 4771,
 'chatting': 1748,
 'allo': 904,
 'braved': 1488,
 'buses': 1573,
 'taken': 6699,
 'trains': 7025,
 'triumphed': 7059,
 'mean': 4413,
 'ham': 3314,
 'jolly': 3853,
 'rest': 5755,
 'week': 7455,
 'wearing': 7439,
 'list': 4147,
 'buyers': 1581,
 'india': 3668,
 'win': 7535,
 'level': 4095,
 'series': 6034,
 'means': 4416,
 'record': 5638,
 'coherently': 1885,
 'twenty': 7106,
 'thought': 6875,
 'misundrstud': 4520,
 'frnd': 3022,
 'knw': 3972,
 'hate': 3356,
 'bt': 1544,
 'wen': 7474,
 'truth': 7074,
 'urself': 7229,
 'gn': 3160,
 'okay': 4911,
 'soon': 6328,
 'over': 5019,
 'best': 1324,
 'sunday': 6609,
 'holiday': 3474,
 'financial': 2863,
 'problem': 5427,
 'missed': 4511,
 'please': 5243,
 'honeybee': 3484,
 'said': 5890,
 'sweetest': 6663,
 'world': 7609,
 'god': 3168,
 'laughed': 4041,
 'wait': 7369,
 'havnt': 3368,
 'met': 4466,
 'person': 5159,
 'reading': 5597,
 'moral': 4580,
 'crack': 2061,
 'jokes': 3850,
 'gm': 3158,
 'ge': 3100,
 'would': 7623,
 'hire': 3444,
 'hitman': 3449,
 'freemsg': 3001,
 'claim': 1822,
 '250': 364,
 'sms': 6268,
 '84025': 659,
 'web2mobile': 7443,
 'mates': 4383,
 'etc': 2651,
 'txt250': 7113,
 '50p': 532,
 'wk': 7569,
 'box139': 1462,
 'la32wu': 3994,
 'remove': 5701,
 'txtx': 7124,
 'yar': 7686,
 'lor': 4212,
 'wan': 7388,
 'horse': 3506,
 'racing': 5541,
 'eat': 2518,
 'ate': 1114,
 'chicken': 1779,
 'rice': 5785,
 '2marrow': 389,
 'coming': 1917,
 'class': 1830,
 'genius': 3110,
 'brother': 1529,
 'his': 3445,
 'skype': 6216,
 'hello': 3399,
 'handsome': 3323,
 'finding': 2865,
 'being': 1304,
 'lazy': 4051,
 'working': 7606,
 'towards': 7013,
 'getting': 3129,
 'net': 4738,
 'mummy': 4640,
 'does': 2385,
 'damn': 2155,
 'tonight': 6978,
 'til': 6908,
 'tomorrow': 6969,
 'nah': 4673,
 'goes': 3170,
 'lives': 4163,
 'here': 3414,
 'though': 6874,
 'birthdate': 1365,
 'certificate': 1714,
 'april': 1033,
 'real': 5599,
 'date': 2177,
 'publish': 5484,
 'shall': 6069,
 'special': 6371,
 'keep': 3916,
 'secret': 5982,
 'thanks': 6816,
 'wishes': 7555,
 'she': 6082,
 'didnt': 2301,
 'search': 5975,
 'online': 4936,
 'let': 4091,
 'know': 3969,
 'dear': 2195,
 'umma': 7146,
 'called': 1613,
 'yun': 7740,
 'buying': 1582,
 'school': 5947,
 'offer': 4893,
 '2000': 342,
 'plus': 5253,
 'only': 4938,
 'jack': 3788,
 'shit': 6103,
 'anything': 995,
 'say': 5933,
 'ask': 1089,
 'helpful': 3406,
 'pretend': 5393,
 'did': 2298,
 'whatever': 7491,
 'response': 5753,
 'hypotheticalhuagauahahuagahyuhagga': 3577,
 'ee': 2538,
 'poortiyagi': 5301,
 'odalebeku': 4887,
 'hanumanji': 3331,
 'name': 4679,
 'hanuman': 3330,
 'bajarangabali': 1202,
 'maruti': 4368,
 'pavanaputra': 5114,
 'sankatmochan': 5908,
 'ramaduth': 5563,
 'mahaveer': 4314,
 'janarige': 3800,
 'ivatte': 3775,
 'kalisidare': 3897,
 'next': 4759,
 'saturday': 5926,
 'olage': 4918,
 'ondu': 4931,
 'news': 4756,
 'keluviri': 3920,
 'maretare': 4355,
 'inde': 3663,
 'dodda': 2383,
 'problum': 5431,
 'nalli': 4678,
 'siguviri': 6166,
 'idu': 3604,
 'matra': 4388,
 'true': 7067,
 'neglet': 4731,
 'cool': 2009,
 'swimming': 6669,
 'pool': 5298,
 'jacuzzi': 3792,
 'house': 3521,
 'jus': 3882,
 'testing': 6795,
 'dunno': 2488,
 'gd': 3099,
 'finish': 2870,
 'bathing': 1243,
 'cleaning': 1835,
 'room': 5829,
 'hospital': 3508,
 'return': 5768,
 'evening': 2664,
 'slowly': 6244,
 'love': 4232,
 'clean': 1834,
 'heart': 3384,
 'blood': 1403,
 'ten': 6776,
 'people': 5141,
 'miracle': 4502,
 'ìï': 7761,
 'oh': 4905,
 'teeth': 6758,
 'paining': 5051,
 'ryder': 5878,
 'unsold': 7194,
 'gibbs': 3134,
 'charge': 1732,
 'when': 7496,
 'get': 3121,
 'checking': 1757,
 'tagged': 6692,
 'friends': 3015,
 'seemed': 5998,
 'count': 2040,
 'sounds': 6348,
 'talents': 6704,
 'dinner': 2328,
 'nt': 4843,
 'ya': 7679,
 'repair': 5712,
 'shop': 6115,
 'reason': 5612,
 'hour': 3519,
 'took': 6983,
 'omw': 4926,
 'easier': 2511,
 'madam': 4303,
 'regret': 5672,
 'disturbance': 2359,
 'reference': 5652,
 'check': 1754,
 'dlf': 2370,
 'premarica': 5374,
 'kindly': 3950,
 'informed': 3681,
 'rgds': 5781,
 'rakhesh': 5559,
 'kerala': 3924,
 'picking': 5199,
 'various': 7267,
 'yeovil': 7702,
 'motor': 4596,
 'project': 5446,
 'hours': 3520,
 '12': 275,
 '30': 414,
 'max': 4396,
 'easy': 2517,
 'advice': 823,
 'ma': 4287,
 'try': 7075,
 'some': 6302,
 'sleep': 6223,
 'imin': 3629,
 'town': 7014,
 'dontmatter': 2413,
 'urgoin': 7224,
 'outl8r': 5010,
 'feathery': 2807,
 'bowa': 1457,
 '07808247860': 36,
 '08719899229': 162,
 '40411': 468,
 '06': 19,
 'vote': 7339,
 'sing': 6180,
 'along': 910,
 'stars': 6455,
 'karaoke': 3904,
 'link': 4136,
 'goal': 3166,
 'arsenal': 1074,
 'henry': 3412,
 'liverpool': 4162,
 'scores': 5952,
 'simple': 6173,
 'shot': 6127,
 'yards': 7688,
 'pass': 5094,
 'bergkamp': 1322,
 'margin': 4357,
 '78': 611,
 'mins': 4496,
 'cry': 2096,
 'stuff': 6547,
 'happens': 3336,
 'top': 6991,
 'everything': 2679,
 'else': 2569,
 'pushes': 5506,
 'edge': 2528,
 'underdtand': 7162,
 'often': 4903,
 'life': 4107,
 'still': 6491,
 've': 7275,
 'finished': 2872,
 'formatting': 2967,
 'tmr': 6937,
 'hu': 3542,
 'also': 915,
 'important': 3636,
 'female': 2824,
 'place': 5224,
 'preferably': 5372,
 'citizen': 1818,
 'smart': 6249,
 'navigate': 4707,
 'through': 6885,
 'choosing': 1803,
 'plan': 5229,
 'require': 5730,
 'guidance': 3277,
 'doubt': 2426,
 'especially': 2645,
 'tbs': 6736,
 'persolvo': 5158,
 'chasing': 1742,
 'since': 6177,
 'sept': 6032,
 'forå': 2976,
 '38': 442,
 'definitely': 2225,
 'paying': 5121,
 'information': 3680,
 'ignore': 3610,
 'kath': 3909,
 'manchester': 4338,
 'first': 2883,
 'daddy': 2151,
 'fetch': 2827,
 'went': 7477,
 'centre': 1708,
 'should': 6128,
 'quite': 5531,
 'diff': 2309,
 'guess': 3274,
 'rite': 5808,
 'zoe': 7750,
 'hit': 3447,
 'fucking': 3040,
 'shitin': 6104,
 'myself': 4664,
 'il': 3617,
 'defo': 2227,
 'hardest': 3344,
 'cum': 2117,
 '2morow': 391,
 'millions': 4483,
 'lekdog': 4079,
 'sending': 6020,
 'mental': 4448,
 'ability': 743,
 'question': 5524,
 'thats': 6826,
 'gentleman': 3113,
 'dignity': 2319,
 'respect': 5748,
 'arnt': 1064,
 'pissed': 5217,
 'off': 4889,
 'really': 5608,
 'xxxxxxxxxxxxxx': 7676,
 'students': 6541,
 'solved': 6301,
 'cat': 1682,
 'xam': 7658,
 'answer': 975,
 'brilliant': 1510,
 '1thing': 333,
 'answr': 980,
 'wipro': 7549,
 'every': 2670,
 'thing': 6855,
 'urgnt': 7223,
 'os': 4991,
 'ubandu': 7132,
 'which': 7505,
 'run': 5867,
 'without': 7564,
 'installing': 3703,
 'hard': 3341,
 'disk': 2352,
 'copy': 2016,
 'files': 2850,
 'system': 6682,
 'coffee': 1884,
 'cake': 1600,
 'promotion': 5454,
 '8714714': 682,
 'awarded': 1163,
 'city': 1819,
 'break': 1493,
 '200': 341,
 'summer': 6604,
 'spree': 6421,
 'store': 6511,
 '88039': 687,
 'skilgme': 6208,
 'tscs087147403231winawk': 7082,
 'age16': 850,
 '50perwksub': 534,
 'winner': 7545,
 '1000': 256,
 'cash': 1673,
 'speak': 6369,
 'live': 4159,
 '087123002209am': 101,
 '7pm': 619,
 '10p': 264,
 'darling': 2170,
 'chat': 1744,
 'why': 7516,
 'sexy': 6054,
 'same': 5905,
 'wrong': 7638,
 'everyso': 2677,
 'panicks': 5059,
 'starts': 6460,
 'goin': 3172,
 'bout': 1456,
 'bein': 1303,
 'û_': 7763,
 'ax': 1168,
 'free2day': 2996,
 'st': 6434,
 'george': 3117,
 'jordan': 3858,
 '89080': 698,
 'saucy': 5927,
 'celeb': 1700,
 'pics': 5201,
 'pocketbabe': 5274,
 '0870241182716': 82,
 'yahoo': 7681,
 'boys': 1479,
 'perf': 5145,
 'legal': 4075,
 'outside': 5013,
 'darren': 2172,
 'course': 2047,
 'nice': 4763,
 'lim': 4123,
 'mp3': 4609,
 'player': 5238,
 'mmm': 4529,
 'fuck': 3037,
 'merry': 4457,
 'christmas': 1810,
 '08702490080': 83,
 'tells': 6768,
 '09066358152': 229,
 '5000': 530,
 'prize': 5420,
 'personal': 5161,
 'details': 2274,
 'prompts': 5455,
 'careful': 1658,
 'oooh': 4945,
 'plenty': 5248,
 'yourself': 7729,
 'always': 921,
 'happy': 3340,
 'becomes': 1279,
 'habit': 3297,
 'finally': 2861,
 'part': 5085,
 'follow': 2930,
 'update_now': 7204,
 'xmas': 7663,
 'latest': 4037,
 'sonyericsson': 6326,
 'bluetooth': 1410,
 'double': 2424,
 'orange': 4973,
 'mobileupd8': 4546,
 '08000839402': 51,
 'call2optout': 1609,
 'f4q': 2745,
 'wednesday': 7451,
 'prof': 5437,
 'passed': 5096,
 'papers': 5068,
 'sem': 6013,
 'congrats': 1969,
 'student': 6539,
 'enna': 2608,
 'kalaachutaarama': 3895,
 'gud': 3271,
 'mrng': 4613,
 'late': 4033,
 'sweet': 6662,
 'dreams': 2443,
 'ummifying': 7147,
 'bye': 1591,
 'wherre': 7503,
 'was': 7404,
 'bathroom': 1244,
 'sup': 6618,
 'worse': 7616,
 'uses': 7238,
 'half': 3308,
 'stops': 6508,
 'him': 3438,
 'complete': 1937,
 'hav': 3360,
 ...}

In [26]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [27]:
np.where(X_train_np[0] !=0)

(array([1242, 1576, 2389, 3210, 3886, 4660, 5691, 6950]),)

In [29]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [31]:
X_test_cv = v.transform(X_test)

In [32]:
from sklearn.metrics import classification_report

In [34]:
y_pred = model.predict(X_test_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       979
           1       0.98      0.92      0.95       136

    accuracy                           0.99      1115
   macro avg       0.99      0.96      0.97      1115
weighted avg       0.99      0.99      0.99      1115